import "@/styles/globals.css";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata = {
  title:
    "VulnTang Clan | The most insecure app on the planet. Try login, XSS, IDOR, traversal, and more! - flag{meta_data_menace}",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="mx-auto max-w-7xl flex flex-col items-center justify-start min-h-screen p-4">
        {children}
      </body>
    </html>
  );
}
